# Generated by Django 4.2.22 on 2025-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
